---
- name: Apply common configuration to all hosts
  hosts: [hacluster]
  remote_user: root

  vars:

     # Packages
     yum_mirror: yum-mirror-centos7.4.1708-serviced-1.5.0.x86_64.rpm
     resmgr_service: zenoss-resmgr-service-6.1.2-1.noarch.rpm
     serviced: serviced-1.5.0-1.x86_64.rpm
     docker: docker-ce-17.09.0.ce-1.el7.centos.x86_64.rpm
     repo_name: zenoss-mirror

     # Site specific configuration
     # dns_server: 10.87.113.13
     hd_device: xvda
     serviced_master: 1
     serviced_dm_basesize: 30G
     # net_iface: ifcfg-eth0

     # Use clean_install to remove all packages and install a new version of Zenoss
     clean_install: false

     # Partid identifies which partition to use for service.
     extended_partid: 3

     # Use ha_metadata for HA configuration. Default 1G
     ha_metadata_partid: 5
     # set partid2 for isvcs
     isvcs_partid: 6
     # set partid3 for serviced pool
     serviced_partid: 7
     # set partid4 for docker pool
     docker_partid: 8

     # Create partitions on system. Set size in GB. Offset partsize
     partid_start_offset:  54GB
     partid_5_size_offset: 55GB
     partid_6_size_offset: 85GB
     partid_7_size_offset: 135GB
     partid_8_size_offset: 165GB


     # Authentication
     zenoss_user: zenoss
     zenoss_passwd: $6$JPK7M6jyGE3gJWNl$hRP907PuVvvHCGXUetg43IuLRxf8HS60HTHjFG2WeXwBbIe3R2I.Kp5ROib2Z/jhR2p5qlx0OX68UF8ZDu/VU1
     hacluster_user: hacluster
     hacluster_password: $6$JPK7M6jyGE3gJWNl$hRP907PuVvvHCGXUetg43IuLRxf8HS60HTHjFG2WeXwBbIe3R2I.Kp5ROib2Z/jhR2p5qlx0OX68UF8ZDu/VU1


  roles:
  - common
  - cluster
