---
- name: Copy docker.conf
  copy: src=files/docker.conf dest=/etc/systemd/system/docker.service.d/

- name: Copy nfs-server.conf 
  copy: src=files/nfs-server.conf dest=/etc/systemd/system/nfs-server.service.d/

- name: Copy dnsmaq.conf
  copy: src=files/dnsmasq.conf dest=/etc/dnsmasq.conf force=yes
  
  notify: daemon-reload 

- meta: flush_handlers 
     
