---
- shell: umount -f /dev/mapper/isvcs-isvcs
  failed_when: false
  no_log: True
  notify: daemon-reload

- meta: flush_handlers

- service: name=serviced state=stopped
  failed_when: False
  no_log: True

- name: Create Control Center internal services filesystem
  lvg:
    vg: isvcs 
    pvs: /dev/{{hd_device}}{{isvcs_partid}}
    state: present
- lvol:
    vg: isvcs
    lv: isvcs
    size: 100%FREE
  failed_when: false
  

- name: Create isvcs XFS filesystem
  filesystem: 
    fstype: xfs
    dev: /dev/mapper/isvcs-isvcs
    force: no


- name: Update isvcs info in fstab
  lineinfile:
    path: /etc/fstab
    regexp: "/opt/serviced/var/isvcs"
    line: "/dev/{{hd_device}}{{isvcs_partid}}   /opt/serviced/var/isvcs     xfs      defaults     0 0"

- name: Mount ISVCS partition
  mount:
     src: /dev/mapper/isvcs-isvcs 
     fstype: xfs
     path: /opt/serviced/var/isvcs
     state: mounted
  
