---
# Partition size is determined by the off-set


- name: Create Extended Partition
  parted:
    device: /dev/{{hd_device}}
    number: "{{ extended_partid }}"
    part_start: "{{ partid_start_offset }}"
    part_end: "100%"
    part_type: extended
    state: present
    unit: GB

- name: Create Logical Partitions
  parted:
    device: /dev/{{hd_device}}
    number: "{{ item.num }}"
    part_start: "{{ item.pstart }}" 
    part_end: "{{ item.pend }}"
    part_type: logical
    state: present
    unit: GB
    #label: gpt

  with_items:
  - { num: "{{ ha_metadata_partid }}", pstart: "{{ partid_start_offset }}", pend: "{{ partid_5_size_offset }}" }
  - { num: "{{ isvcs_partid }}", pstart: "{{ partid_5_size_offset }}", pend: "{{ partid_6_size_offset }}"  }
  - { num: "{{ serviced_partid }}", pstart: "{{ partid_6_size_offset }}", pend: "{{  partid_7_size_offset }}" }
  - { num: "{{ docker_partid }}", pstart: "{{ partid_7_size_offset }}", pend: "{{ partid_8_size_offset }}" }
 


  notify: daemon-reload


- meta: flush_handlers

