- name: Disable SELinux
  selinux:
    state: disabled
  register: selinux_enforcing

- name: Reboot Server
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: selinux_enforcing.changed

- name: Wait for server online after reboot
  wait_for_connection:
    sleep: 5
    delay: 5
    timeout: 600
    
- shell: dhclient 

  when: selinux_enforcing.changed
