---
# systemd-logind and systemd-journald reports SIGABORT
# when doing system updates
#
- name: Disable firewalld
  service: name=firewalld state=stopped enabled=no

- name: Disable Kernel Updates
  lineinfile:
    state: present
    path: /etc/yum.conf
    regexp: '^exclude*'
    line: 'exclude=kernel*'

- name: Install System Updates
  yum: name='*' state=latest
  register: system_update

- name: Install ntp / nfs
  yum:
    name: ['ntp','nfs-utils','libnfsidmap']
    state: latest

- name: Start and enble ntpd / nfs-server
  service: name="{{item}}" state=started enabled=yes
  with_items:
  - "ntpd"
  - "rpcbind"
  - "nfs-server"
  - "rpc-statd"
  - "nfs-idmapd"

- name: Install yum utils
  yum: 
    name: ['yum-utils'] 
    state: latest

- name: Install elrepo GPG key
  rpm_key:
    state: present
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

- name: Install elrepo
  yum_repository:
    name: elrepo
    description: ELRepo.org Community Enterprise Linux Repository - el7
    baseurl: http://elrepo.org/linux/elrepo/el7/$basearch/
    mirrorlist: http://mirrors.elrepo.org/mirrors-elrepo.el7
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org
    gpgcheck: yes

- name: Install elrepo-testing
  yum_repository:
    name: elrepo-testing
    description: ELRepo.org Community Enterprise Linux Testing Repository - el7
    baseurl: http://elrepo.org/linux/testing/el7/$basearch/
    mirrorlist: http://mirrors.elrepo.org/mirrors-elrepo-testing.el7
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org
    gpgcheck: yes

- name: Install elrepo-kernel
  yum_repository:
    name: elrepo-kernel
    description: ELRepo.org Community Enterprise Linux Kernel Repository - el7
    baseurl: http://elrepo.org/linux/kernel/el7/$basearch/
    mirrorlist: http://mirrors.elrepo.org/mirrors-elrepo-kernel.el7
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org
    enabled: no
    gpgcheck: yes

- name: Install elrepo-extras
  yum_repository:
    name: elrepo-extras
    description: ELRepo.org Community Enterprise Linux Extras Repository - el7
    baseurl: http://elrepo.org/linux/extras/el7/$basearch/
    mirrorlist: http://mirrors.elrepo.org/mirrors-elrepo-extras.el7
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org
    enabled: no
    gpgcheck: yes

