---

- name: Create /etc/sysconfig/docker 
  lineinfile:
    state: present
    create: yes
    path: /etc/sysconfig/docker
    regexp: '^OPTIONS'
#    line: 'OPTIONS="--log-level=error --storage-driver devicemapper --exec-opt native.cgroupdriver=cgroupfs --storage-opt dm.mountopt=discard --storage-opt dm.thinpooldev=/dev/mapper/docker-docker--pool --dns={{docker_dns.stdout}} --bip={{docker_bip.stdout}}"'
    line: 'OPTIONS="--log-level=error --insecure-registry={{ inventory_hostname }}:5000 --storage-driver devicemapper --exec-opt native.cgroupdriver=cgroupfs --storage-opt dm.mountopt=discard --storage-opt dm.thinpooldev=/dev/mapper/docker-docker--pool --dns=172.17.0.1 --bip=172.17.0.1/16"'

- name: Create_thin_pools_docker
  shell: serviced-storage create-thin-pool docker /dev/{{hd_device}}{{docker_partid}}

  notify: daemon-reload

- meta: flush_handlers


- name : Start Docker
  service:  
    name: docker 
    state: started 
    enabled: yes 

- shell: ip addr show docker0 | awk '/[0-9]{,3}\.[0-9]{,3}\.[0-9]{,3}\.[0-9]{,3}/ {print $2}'
  register: docker_bip

- shell: echo "{{docker_bip.stdout}}" | cut -d '/' -f1
  register: docker_dns

- debug:
    msg: 'docker_bip: {{docker_bip.stdout}} and docker_dns: {{docker_dns.stdout}}'
