---
# Partition size is determined by the off-set


- name: Create Partitions
  parted:
    device: /dev/{{hd_device}}
    number: "{{ item.num }}"
    part_start: "{{ item.pstart }}" 
    part_end: "{{ item.pend }}"
    state: present
    label: gpt

  with_items:
  - { num: "{{ ha_metadata_partid }}", pstart: "1MiB", pend: "{{ partid_1_size_offset }}" }
  - { num: "{{ isvcs_partid }}", pstart: "{{ partid_1_size_offset }}", pend: "{{ partid_2_size_offset }}"  }
  - { num: "{{ serviced_partid }}", pstart: "{{ partid_2_size_offset }}", pend: "{{  partid_3_size_offset }}" }
  - { num: "{{ docker_partid }}", pstart: "{{ partid_3_size_offset }}", pend: "{{ partid_4_size_offset }}" }
 


  notify: daemon-reload


- meta: flush_handlers

