---
- 
  shell: umount -f /dev/mapper/isvcs-isvcs
  failed_when: false
  no_log: True
  notify: daemon-reload

- meta: flush_handlers

- service: name=serviced state=stopped
  failed_when: False
  no_log: True

- service: name=docker   state=stopped
  failed_when: False
  no_log: True

- service: name=ntpd  state=stopped
  failed_when: False
  no_log: True
  
- service: name=nfs  state=stopped
  failed_when: False
  no_log: True


# To find problem container using devicemapper
# find /proc/*/mounts | xargs grep "container id"
# ps -p pid 
- shell: umount -A --recursive /dev/mapper/docker-253\:* 2> /dev/null; dmsetup remove /dev/mapper/docker-253\:* 2> /dev/null
  failed_when: False
  no_log: True


- shell: ls -d  /opt/serviced/var/volumes/* 2> /dev/null
  register: volume_name
  failed_when: False
  no_log: True

- file:
    state: absent
    path: "{{item}}"
  with_items:
  - /opt/serviced/var/volumes/.devicemapper
  - "{{volume_name.stdout_lines}}"
  - /var/lib/docker/devicemapper
  - /var/lib/docker/image/devicemapper
  - /var/lib/docker/volumes/.devicemapper

  failed_when: False
  no_log: True
   

- name: Remove LVM volume Group
  lvg: vg=docker state=absent force=yes

- lvg: vg=isvcs  state=absent force=yes

- lvg: vg=serviced state=absent force=yes


# Read device information (always use unit when probing)
- name: Delete Partitions
  parted: device=/dev/{{hd_device}} unit=MiB
  register: sdb_info

# Remove all partitions from disk
- parted:
    device: /dev/{{hd_device}}
    number: "{{ item.num }}"
    state: absent
  with_items:
  - "{{ sdb_info.partitions }}"
